services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:liXg9k39Ovt9F1r@mysql:3306/xcoin_database
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: liXg9k39Ovt9F1r
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: xcoin_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mjlsbkCh2z8Ft63
    command: ["redis-server", "--requirepass", "mjlsbkCh2z8Ft63"]

volumes:
  mysql_data:
