name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:     # allows manual run from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/eminentbit/xcoin-transfer.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync with upstream"
          git push origin main
